CREATE TABLE `feed` (
	`no` INT(10) NOT NULL AUTO_INCREMENT,
	`id` VARCHAR(50) NULL DEFAULT NULL,
	`content` LONGTEXT NULL DEFAULT NULL ,
	`ts` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`no`) USING BTREE
)
ENGINE=InnoDB
;

CREATE TABLE `user` (
	`id` VARCHAR(128) NOT NULL,
	`password` VARCHAR(32) NULL DEFAULT NULL,
	`name` VARCHAR(32) NULL DEFAULT NULL,
	`ts` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`) USING BTREE
)
ENGINE=InnoDB
;